In [1]:
import requests
import pandas as pd 
import numpy as np 
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import time 
import calendar

In [2]:
def bearish_reversal(data):
    global shooting_star,bearish_engulfing,advance_block,hanging_man,tweezer_top,evening_star
    if data["close"].iloc[-3]<data["close"].iloc[-2]<data["close"].iloc[-1]:  # Shooting Star
        if data["color"].iloc[-1]==0: 
            if data["upper_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
                if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
                    shooting_star+=1
                    return 1
    if data["color"].iloc[-2]==1:
        if data["color"].iloc[-1]==0:
            if data["abs_body"].iloc[-1]>data["abs_body"].iloc[-2]:
                    bearish_engulfing+=1
                    return 2
    if all(data["color"].iloc[-3:]==1):  # Advance Block
        if data["body"].iloc[-3]>data["body"].iloc[-2]:
            if data["body"].iloc[-2]>data["body"].iloc[-1]:
                advance_block+=1
                return 3
    if data["color"].iloc[-1]==0:  # Hanging Man
        if data["lower_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
            if data["upper_wick"].iloc[-1]<0.2*data["lower_wick"].iloc[-1]:
                hanging_man+=1
                return 4
    if data["color"].iloc[-1]==0:  # Tweezer Top
        if data["color"].iloc[-2]==1:
            if data["abs_body"].iloc[-1]<data["abs_body"].iloc[-2]:
                if 0.99*data["high"].iloc[-1]<data["high"].iloc[-2]<1.01*data["high"].iloc[-1]:
                    tweezer_top+=1  
                    return 5
    if data["color"].iloc[-3]==1:  # Evening Star
        if data["color"].iloc[-1]==0:
            if data["upper_wick"].iloc[-3]+data["lower_wick"].iloc[-3]<data["abs_body"].iloc[-3]:
                if data["upper_wick"].iloc[-1]+data["lower_wick"].iloc[-1]<data["abs_body"].iloc[-1]:
                    if data["abs_body"].iloc[-2]<0.2*data["upper_wick"].iloc[-2]:
                        if data["abs_body"].iloc[-2]<0.2*data["lower_wick"].iloc[-2]:
                            evening_star+=1
                            return 6
    return 0

In [3]:
def bullish_reversal(data):
    global hammer,inverted_hammer,bullish_engulfing,three_stars_in_the_south,tweezer_bottom,morning_star
    if data["color"].iloc[-1]==1:  # Hammer
        if data["lower_wick"].iloc[-1]>2*data["body"].iloc[-1]:
            if data["upper_wick"].iloc[-1]<0.2*data["lower_wick"].iloc[-1]:
                hammer+=1
                return 1
    if data["color"].iloc[-1]==1:  # Inverted Hammer
        if data["upper_wick"].iloc[-1]>2*data["body"].iloc[-1]:
            if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
                inverted_hammer+=1
                return 2
    if data["color"].iloc[-2]==0:  # Bullish Engulfing
        if data["abs_body"].iloc[-2]>data["upper_wick"].iloc[-2]:
            if data["abs_body"].iloc[-2]>data["lower_wick"].iloc[-2]:
                if data["color"].iloc[-1]==1:
                    if data["body"].iloc[-1]>data["upper_wick"].iloc[-1]:
                        if data["body"].iloc[-1]>data["lower_wick"].iloc[-1]:
                            if data["body"].iloc[-1]>data["body"].iloc[-2]:
                                bullish_engulfing+=1
                                return 3
    if all(data["color"].iloc[-3:]==0):  # Three Stars in the South
        if data["abs_body"].iloc[-3]>data["abs_body"].iloc[-2]:
            if data["abs_body"].iloc[-2]>data["abs_body"].iloc[-1]:
                three_stars_in_the_south+=1
                return 4
    if data["color"].iloc[-1]==1:  # Tweezer Bottom
        if data["color"].iloc[-2]==0:
            if data["abs_body"].iloc[-1]>data["abs_body"].iloc[-2]:
                if 0.9*data["lower_wick"].iloc[-1]<data["lower_wick"].iloc[-2]<1.1*data["lower_wick"].iloc[-1]:
                    tweezer_bottom+=1
                    return 5
    if data["color"].iloc[-3]==0:  # Morning Star
        if data["color"].iloc[-1]==1:
            if data["upper_wick"].iloc[-3]+data["lower_wick"].iloc[-3]<data["abs_body"].iloc[-3]:
                if data["upper_wick"].iloc[-1]+data["lower_wick"].iloc[-1]<data["abs_body"].iloc[-1]:
                    if data["abs_body"].iloc[-2]<0.2*data["upper_wick"].iloc[-2]:
                        if data["abs_body"].iloc[-2]<0.2*data["lower_wick"].iloc[-2]:
                            morning_star+=1
                            return 6
    return 0

In [4]:
def bearish_continuation(data):
    global bearish_three_line_strike,falling_three_methods,bearish_mat_hold
    if data["color"].iloc[-4]==0:  # Bearish Three Line Strike 
        if data["color"].iloc[-3]==0:   
            if data["color"].iloc[-2]==0:
                if data["color"].iloc[-1]==1:
                    if data["abs_body"].iloc[-1]>(data["abs_body"].iloc[-4]+data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]):
                        bearish_three_line_strike+=1
                        return 1
    if data["color"].iloc[-5]==0:  # Falling Three Methods 
        if data["color"].iloc[-4]==1:
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                            if data["close"].iloc[-2]-data["open"].iloc[-4]<data["open"].iloc[-5]-data["close"].iloc[-5]:
                                if data["close"].iloc[-1]<data["close"].iloc[-5]:
                                    falling_three_methods+=1
                                    return 2
    if data["color"].iloc[-5]==0:  # Bearish Mat Hold
        if data["color"].iloc[-4]==1:
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                            if data["open"].iloc[-4]<data["close"].iloc[-5]:
                                if data["high"].iloc[-2]-data["low"].iloc[-4]<data["high"].iloc[-5]-data["low"].iloc[-5]:
                                    if data["close"].iloc[-1]<data["low"].iloc[-5]:
                                        bearish_mat_hold+=1
                                        return 3
    return 0

In [5]:
def bullish_continuation(data):
        global bullish_three_line_strike,rising_three_methods,bullish_mat_hold
        if data["color"].iloc[-4]==1:  # Bullish Three Line Strike 
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["abs_body"].iloc[-1]>(data["abs_body"].iloc[-4]+data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]):
                            bullish_three_line_strike+=1
                            return 1
        if data["color"].iloc[-5]==1:  # Rising Three Methods 
            if data["color"].iloc[-4]==0:
                if data["color"].iloc[-3]==0:
                    if data["color"].iloc[-2]==0:
                        if data["color"].iloc[-1]==1:
                            if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                                if data["open"].iloc[-4]-data["close"].iloc[-2]<data["close"].iloc[-5]-data["open"].iloc[-5]:
                                    if data["close"].iloc[-1]>data["close"].iloc[-5]:
                                        rising_three_methods+=1
                                        return 2 
        if data["color"].iloc[-5]==1:  # Bullish Mat Hold
            if data["color"].iloc[-4]==0:
                if data["color"].iloc[-3]==0:
                    if data["color"].iloc[-2]==0:
                        if data["color"].iloc[-1]==1:
                            if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                                if data["open"].iloc[-4]>data["close"].iloc[-5]:
                                    if data["high"].iloc[-4]-data["low"].iloc[-2]<data["high"].iloc[-5]-data["low"].iloc[-5]:
                                        if data["close"].iloc[-1]>data["high"].iloc[-5]:
                                            bullish_mat_hold+=1
                                            return 3
        return 0

In [6]:
data=[]
api_key='e62c395ec9844095ada4b688d012a975'
technical='time_series'
ticker='BTC/USD'
timezone='Asia/Calcutta'
interval='30min'
for yr in range(2022,2026):
    for m in range(1,5): 
        last_day=calendar.monthrange(yr,3*m)[1]   
        start_date=f'{yr}-{(3*m-2):02d}-01T00:00:00'
        end_date=f'{yr}-{(3*m):02d}-{last_day}T23:30:00'
        api_url=f'https://api.twelvedata.com/{technical}?symbol={ticker}&order=asc&timezone={timezone}&start_date={start_date}&end_date={end_date}&interval={interval}&outputsize=5000&apikey={api_key}'
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if "values" in fetch:
                df=pd.DataFrame(fetch['values'])
                data.append(df)
                time.sleep(8)
                break
            elif "code" in fetch and fetch["code"]==429:
                print("Rate limit exceeded")
                time.sleep(15)
            else: 
                print("API Error:",fetch)
                fetch=None
                break
data=pd.concat(data,ignore_index=True)
data['color']=np.where(data['close']>data['open'],1,0)
data['open']=pd.to_numeric(data['open'])
data['close']=pd.to_numeric(data['close'])
data['abs_body']=abs(data['close']-data['open'])
data['body']=(data['close']-data['open'])
data['high']=pd.to_numeric(data['high'])
data['low']=pd.to_numeric(data['low'])
data['upper_wick']=np.where(data['color']==1,data['high']-data['close'],data['high']-data['open'])
data['lower_wick']=np.where(data['color']==1,data['open']-data['low'],data['close']-data['low'])
data=data.dropna()
data=data.reset_index(drop=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
69992,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000
69993,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000
69994,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000
69995,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000
69996,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000

In [7]:
data['datetime']=pd.to_datetime(data['datetime'])
missing_times=pd.date_range("2022-01-01", "2025-12-31 23:30", freq="30T").difference(data['datetime'])
missing_times

C:\Users\#samay\AppData\Local\Temp\ipykernel_33832\2112058808.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  missing_times=pd.date_range("2022-01-01", "2025-12-31 23:30", freq="30T").difference(data['datetime'])

DatetimeIndex(['2022-02-19 19:30:00', '2022-02-19 20:00:00',
               '2022-02-19 20:30:00', '2022-02-19 21:00:00',
               '2022-02-19 21:30:00', '2022-02-19 22:00:00',
               '2022-02-19 22:30:00', '2022-02-19 23:00:00',
               '2022-02-19 23:30:00', '2022-02-20 00:00:00',
               ...
               '2025-10-25 21:30:00', '2025-10-25 22:00:00',
               '2025-10-25 22:30:00', '2025-10-25 23:00:00',
               '2025-10-25 23:30:00', '2025-10-26 00:00:00',
               '2025-10-26 00:30:00', '2025-10-26 01:00:00',
               '2025-10-26 01:30:00', '2025-10-26 02:00:00'],
              dtype='datetime64[ns]', length=131, freq=None)

In [8]:
missing_times=pd.date_range(start="2022-02-19 19:30",end="2022-02-19 23:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[40417.019531, 40382.390620, 40495.820310, 40316.121090, 39856.980470, 40183.230470, 39976.660160, 40073.031250, 40052.289060],
    "high":[40497.32812, 40449.48047, 40739.82031, 40316.12109, 40377.17188, 40382.75, 40360.03125, 40164.83984, 40052.28906],
    "low":[40316.82031, 39673.44922, 40278.39844, 39693.89844, 39464.60938, 40004.41016, 39976.66016, 39963.35156, 39825.62109],
    "close":[40354.148440, 40437.609380, 40278.398440, 39790.531250, 40153.898440, 40004.410160, 40095.351560, 40032.710940, 39983.800780],
    "abs_body":[62.871091,55.21876,217.42187,525.58984,296.91797,178.82031,118.6914,40.32031,68.48828],
    "body":[-62.871091,55.21876,-217.42187,-525.58984,296.91797,-178.82031,118.6914,-40.32031,-68.48828]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70001,2022-02-19 21:30:00,39856.980470,40377.17188,39464.60938,40153.89844,NaN,296.917970,296.917970,NaN,NaN
70002,2022-02-19 22:00:00,40183.230470,40382.75000,40004.41016,40004.41016,NaN,178.820310,-178.820310,NaN,NaN
70003,2022-02-19 22:30:00,39976.660160,40360.03125,39976.66016,40095.35156,NaN,118.691400,118.691400,NaN,NaN
70004,2022-02-19 23:00:00,40073.031250,40164.83984,39963.35156,40032.71094,NaN,40.320310,-40.320310,NaN,NaN
70005,2022-02-19 23:30:00,40052.289060,40052.28906,39825.62109,39983.80078,NaN,68.488280,-68.488280,NaN,NaN

In [9]:
missing_times=pd.date_range(start="2022-02-20 00:00",end="2022-02-20 02:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[39966.011719,40165.44922,40245.16016,40225.78125,40079.87891,39969.53906],
    "high":[40194.71875,40268.60156,40353.83984,40294.37891,40178.96094,40149.51172],
    "low":[39943.26172,40084.64062,40094.92969,40050.39062,39960.55859,39916.57031],
    "close":[40193.53906,40268.60156,40218.44141,40123.28125,39966.98828,40128.75],
    "abs_body":[227.527341,103.15234,26.71875,102.5,112.890630,159.21094],
    "body":[227.527341,103.15234,-26.71875,-102.5,-112.890630,159.21094]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70007,2022-02-20 00:30:00,40165.449220,40268.60156,40084.64062,40268.60156,NaN,103.152340,103.152340,NaN,NaN
70008,2022-02-20 01:00:00,40245.160160,40353.83984,40094.92969,40218.44141,NaN,26.718750,-26.718750,NaN,NaN
70009,2022-02-20 01:30:00,40225.781250,40294.37891,40050.39062,40123.28125,NaN,102.500000,-102.500000,NaN,NaN
70010,2022-02-20 02:00:00,40079.878910,40178.96094,39960.55859,39966.98828,NaN,112.890630,-112.890630,NaN,NaN
70011,2022-02-20 02:30:00,39969.539060,40149.51172,39916.57031,40128.75000,NaN,159.210940,159.210940,NaN,NaN

In [10]:
missing_times=pd.date_range(start="2022-04-03 02:00",end="2022-04-03 02:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[46324.46094],
    "high":[46391.42188],
    "low":[46111.011719],
    "close":[46164.92969],
    "abs_body":[159.53125],
    "body":[-159.53125]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70008,2022-02-20 01:00:00,40245.160160,40353.83984,40094.929690,40218.44141,NaN,26.718750,-26.718750,NaN,NaN
70009,2022-02-20 01:30:00,40225.781250,40294.37891,40050.390620,40123.28125,NaN,102.500000,-102.500000,NaN,NaN
70010,2022-02-20 02:00:00,40079.878910,40178.96094,39960.558590,39966.98828,NaN,112.890630,-112.890630,NaN,NaN
70011,2022-02-20 02:30:00,39969.539060,40149.51172,39916.570310,40128.75000,NaN,159.210940,159.210940,NaN,NaN
70012,2022-04-03 02:00:00,46324.460940,46391.42188,46111.011719,46164.92969,NaN,159.531250,-159.531250,NaN,NaN

In [11]:
missing_times=pd.date_range(start="2022-05-06 00:30",end="2022-05-06 01:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[39601.14844,39844.64062],
    "high":[39972.55078,39903.19922],
    "low":[39545.058594,39671.89844],
    "close":[39840.53906,39816.12109],
    "abs_body":[239.39062,28.51953],
    "body":[239.39062,-28.51953]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70010,2022-02-20 02:00:00,40079.878910,40178.96094,39960.558590,39966.98828,NaN,112.890630,-112.890630,NaN,NaN
70011,2022-02-20 02:30:00,39969.539060,40149.51172,39916.570310,40128.75000,NaN,159.210940,159.210940,NaN,NaN
70012,2022-04-03 02:00:00,46324.460940,46391.42188,46111.011719,46164.92969,NaN,159.531250,-159.531250,NaN,NaN
70013,2022-05-06 00:30:00,39601.148440,39972.55078,39545.058594,39840.53906,NaN,239.390620,239.390620,NaN,NaN
70014,2022-05-06 01:00:00,39844.640620,39903.19922,39671.898440,39816.12109,NaN,28.519530,-28.519530,NaN,NaN

In [12]:
missing_times=pd.date_range(start="2022-10-22 17:30",end="2022-10-22 18:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[18947.509770,18783.619140,18870.109380],
    "high":[18947.50977,18884.25,19004.060547],
    "low":[18679.75,18734.41016,18870.10938],
    "close":[18782.14062,18884.25,18962.26953],
    "abs_body":[165.369150,100.630860,92.16015],
    "body":[-165.369150,100.630860,92.160150]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70013,2022-05-06 00:30:00,39601.148440,39972.550780,39545.058594,39840.53906,NaN,239.390620,239.390620,NaN,NaN
70014,2022-05-06 01:00:00,39844.640620,39903.199220,39671.898440,39816.12109,NaN,28.519530,-28.519530,NaN,NaN
70015,2022-10-22 17:30:00,18947.509770,18947.509770,18679.750000,18782.14062,NaN,165.369150,-165.369150,NaN,NaN
70016,2022-10-22 18:00:00,18783.619140,18884.250000,18734.410160,18884.25000,NaN,100.630860,100.630860,NaN,NaN
70017,2022-10-22 18:30:00,18870.109380,19004.060547,18870.109380,18962.26953,NaN,92.160150,92.160150,NaN,NaN

In [13]:
missing_times=pd.date_range(start="2022-11-17 04:30",end="2022-11-17 05:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16861.900390,16844.580080,16880.15039],
    "high":[16877.58984,16882.83008,16911.92969],
    "low":[16824.43945,16820.90039,16782.50977],
    "close":[16839.30078,16880.15039,16782.50977],
    "abs_body":[22.599610,35.570310,97.640620],
    "body":[-22.599610,35.570310,-97.640620]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70016,2022-10-22 18:00:00,18783.619140,18884.250000,18734.41016,18884.25000,NaN,100.630860,100.630860,NaN,NaN
70017,2022-10-22 18:30:00,18870.109380,19004.060547,18870.10938,18962.26953,NaN,92.160150,92.160150,NaN,NaN
70018,2022-11-17 04:30:00,16861.900390,16877.589840,16824.43945,16839.30078,NaN,22.599610,-22.599610,NaN,NaN
70019,2022-11-17 05:00:00,16844.580080,16882.830080,16820.90039,16880.15039,NaN,35.570310,35.570310,NaN,NaN
70020,2022-11-17 05:30:00,16880.150390,16911.929690,16782.50977,16782.50977,NaN,97.640620,-97.640620,NaN,NaN

In [14]:
missing_times=pd.date_range(start="2022-11-18 05:00",end="2022-11-18 10:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16844.580080,16880.15039,16681.929690,16688.31055,16697.230470,16684.380860,16653.359380,16584.320310,16580.169920,16508.189450,16470.33008],
    "high":[16882.83008,16911.92969,16711.84961,16727.19922,16710.41992,16691.91016,16672.31055,16593.53906,16582.75977,16509.92969,16519.50977],
    "low":[16820.90039,16782.50977,16660.23047,16681.28906,16671.66992,16642.070312,16582.31055,16568.24023,16498.17969,16403.44922,16467.25],
    "close":[16880.15039,16782.50977,16688.230470,16697.349610,16680.490230,16655.009766,16582.310550,16583.050781,16502.509770,16472.599610,16489.439450],
    "abs_body":[35.570310,97.640620,6.30078,9.03906,16.74024,29.371094,71.04883,1.269529,77.660150,35.589840,19.109370],
    "body":[35.570310,-97.640620,6.300780,9.039060,-16.740240,-29.371094,-71.048830,-1.269529,-77.660150,-35.589840,19.109370]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70027,2022-11-18 08:00:00,16653.359380,16672.31055,16582.31055,16582.310550,NaN,71.048830,-71.048830,NaN,NaN
70028,2022-11-18 08:30:00,16584.320310,16593.53906,16568.24023,16583.050781,NaN,1.269529,-1.269529,NaN,NaN
70029,2022-11-18 09:00:00,16580.169920,16582.75977,16498.17969,16502.509770,NaN,77.660150,-77.660150,NaN,NaN
70030,2022-11-18 09:30:00,16508.189450,16509.92969,16403.44922,16472.599610,NaN,35.589840,-35.589840,NaN,NaN
70031,2022-11-18 10:00:00,16470.330080,16519.50977,16467.25000,16489.439450,NaN,19.109370,19.109370,NaN,NaN

In [15]:
missing_times=pd.date_range(start="2022-11-19 05:00",end="2022-11-19 19:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16844.58008,16880.15039,16681.92969,16688.31055,16697.23047,16684.38086,16653.35938,16584.32031,16580.16992,16508.18945,16470.33008,16825.42969,16810.34961,16791.14062,16744.73047,16778.31055,16767.76953,16727.86914,16711.51953,16715.65039,16727.16992,16730.38086,16781.96094,16750.039062,16736.25977,16737.16016,16754.5293,16759.91992,16777.41992,16742.2793],
    "high":[16882.83008,16911.92969,16711.84961,16727.19922,16710.41992,16691.91016,16672.31055,16593.53906,16582.75977,16509.92969,16519.50977,16825.42969,16815.41016,16806.4707,16788.050781,16785.25977,16770.11914,16731.35938,16721.9707,16740.089844,16745.68945,16789,16833.86914,16769.050781,16746.17969,16764.41992,16771.84961,16798.17969,16796.070312,16765.97070],
    "low":[16820.90039,16782.50977,16660.23047,16681.28906,16671.66992,16642.070312,16582.31055,16568.24023,16498.17969,16403.44922,16467.25,16806.82031,16772.98047,16744.21094,16743.75,16751.63086,16708.80078,16663.88086,16688.91016,16711.58984,16707.10938,16726.96094,16708.39062,16726.63086,16702.25977,16730.90039,16745.53906,16759.91992,16724.74023,16730.83008],
    "close":[16880.15039,16782.50977,16688.23047,16697.34961,16680.49023,16655.009766,16582.31055,16583.050781,16502.50977,16472.59961,16489.43945,16806.82031,16789.84961,16749.4707,16778.58984,16770.11914,16731.13086,16712.51953,16714.67969,16728.48047,16729.35938,16775.28906,16756.53906,16737.25,16737.83984,16753.91992,16764.2207,16777.070312,16744.66016,16759.94922],
    "abs_body":[35.57031,97.64062,6.30078,9.03906,16.74024,29.371094,71.04883,1.269529,77.66015,35.58984,19.10937,18.609380,20.5,41.66992,33.85937,8.19141,36.63867,15.34961,3.16016,12.83008,2.18946,44.9082,25.42188,12.789062,1.58007,16.75976,9.6914,17.150392,32.75976,17.66992],
    "body":[35.57031,-97.64062,6.30078,9.03906,-16.74024,-29.371094,-71.04883,-1.269529,-77.66015,-35.58984,19.10937,-18.609380,-20.5,-41.66992,33.85937,-8.19141,-36.63867,-15.34961,3.16016,12.83008,2.18946,44.9082,-25.42188,-12.789062,1.58007,16.75976,9.6914,17.150392,-32.75976,17.66992]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70057,2022-11-19 17:30:00,16737.160160,16764.419920,16730.90039,16753.919920,NaN,16.759760,16.759760,NaN,NaN
70058,2022-11-19 18:00:00,16754.529300,16771.849610,16745.53906,16764.220700,NaN,9.691400,9.691400,NaN,NaN
70059,2022-11-19 18:30:00,16759.919920,16798.179690,16759.91992,16777.070312,NaN,17.150392,17.150392,NaN,NaN
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.660160,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.949220,NaN,17.669920,17.669920,NaN,NaN

In [16]:
missing_times=pd.date_range(start="2022-11-20 14:30",end="2022-11-20 15:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16715.65039,16727.16992],
    "high":[16740.089844,16745.68945],
    "low":[16711.58984,16707.10938],
    "close":[16728.48047,16729.35938],
    "abs_body":[12.83008,2.18946],
    "body":[12.83008,2.18946]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70059,2022-11-19 18:30:00,16759.919920,16798.179690,16759.91992,16777.070312,NaN,17.150392,17.150392,NaN,NaN
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.660160,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.949220,NaN,17.669920,17.669920,NaN,NaN
70062,2022-11-20 14:30:00,16715.650390,16740.089844,16711.58984,16728.480470,NaN,12.830080,12.830080,NaN,NaN
70063,2022-11-20 15:00:00,16727.169920,16745.689450,16707.10938,16729.359380,NaN,2.189460,2.189460,NaN,NaN

In [17]:
missing_times=pd.date_range(start="2022-11-20 16:00",end="2022-11-20 16:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16730.38086],
    "high":[16789],
    "low":[16726.96094],
    "close":[16775.28906],
    "abs_body":[44.9082],
    "body":[44.9082]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70060,2022-11-19 19:00:00,16777.419920,16796.070312,16724.74023,16744.66016,NaN,32.759760,-32.759760,NaN,NaN
70061,2022-11-19 19:30:00,16742.279300,16765.970700,16730.83008,16759.94922,NaN,17.669920,17.669920,NaN,NaN
70062,2022-11-20 14:30:00,16715.650390,16740.089844,16711.58984,16728.48047,NaN,12.830080,12.830080,NaN,NaN
70063,2022-11-20 15:00:00,16727.169920,16745.689450,16707.10938,16729.35938,NaN,2.189460,2.189460,NaN,NaN
70064,2022-11-20 16:00:00,16730.380860,16789.000000,16726.96094,16775.28906,NaN,44.908200,44.908200,NaN,NaN

In [18]:
missing_times=pd.date_range(start="2022-12-03 13:00",end="2022-12-03 16:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[16932.40039,16958.76953,16948.029297,16967.91016,16965.92969,16967.32031,16954.35938,16967.060547],
    "high":[16970.65039,16965.75977,16972.85938,16978.36914,16988.4707,16977.070312,16968.7207,16995.019531],
    "low":[16932.40039,16941.59961,16948.029297,16960.82031,16964.58984,16952.78906,16951.17969,16959.36914],
    "close":[16965.30078,16947.4707,16966.25977,16966.46094,16966.029297,16954.82031,16966.88086,16974.080078],
    "abs_body":[32.90039,11.29883,18.230473,1.44922,0.099607,12.5,12.52148,7.019531],
    "body":[32.90039,-11.29883,-18.230473,-1.44922,0.099607,-12.5,12.52148,7.019531]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.17969,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.00000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.55078,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.42969,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.94922,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70068,2022-12-03 14:30:00,16967.910160,16978.369140,16960.82031,16966.460940,NaN,1.449220,-1.449220,NaN,NaN
70069,2022-12-03 15:00:00,16965.929690,16988.470700,16964.58984,16966.029297,NaN,0.099607,0.099607,NaN,NaN
70070,2022-12-03 15:30:00,16967.320310,16977.070312,16952.78906,16954.820310,NaN,12.500000,-12.500000,NaN,NaN
70071,2022-12-03 16:00:00,16954.359380,16968.720700,16951.17969,16966.880860,NaN,12.521480,12.521480,NaN,NaN
70072,2022-12-03 16:30:00,16967.060547,16995.019531,16959.36914,16974.080078,NaN,7.019531,7.019531,NaN,NaN

In [19]:
missing_times=pd.date_range(start="2023-02-22 21:30",end="2023-02-23 11:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[24563.85938,24381.33984,24409.80078,24401.59961,24641.91016,24629.23047,24689.48047,24640.019531,24607.7207,24449.66992,24459.94922,24241.070312,24190.16992,24295.82031,24389,24361.81055,24452.98047,24412.73047,24403.23047,24360.14062,24203.83984,24036.24023,24172.31055,24229.11914,24201.96094,24163.82031,24158.83984,24026.33008,24102.78906],
    "high":[24587.75977,24444.42969,24444.65039,24652.85938,24746.90039,24732.019531,24693.90039,24686.53906,24642.88086,24525.67969,24536.65039,24332.26953,24316.30078,24428.84961,24404.33984,24451.90039,24474.51953,24425.5293,24432.75,24392.070312,24203.83984,24195.30078,24270.40039,24247.11914,24222.73047,24170.32031,24168.15039,24113.029297,24128.25977],
    "low":[24321.32031,24301.5293,24380.76953,24401.59961,24589.96094,24569.58008,24564.4707,24558.17969,24450.56055,24434.57031,24159.85938,24173.41016,24174.28906,24280.82031,24341.019531,24351.32031,24411.49023,24276.41016,24356.019531,24156.5,23969.66016,23873.0097656,24133.11914,24155.86914,24160.029297,24031.099609,24007.91992,24013.31055,24028.17969],
    "close":[24377.19922,24403.060547,24412.69922,24652.85938,24631.66016,24693.90039,24636.63086,24595.96094,24450.88086,24464.41016,24257.78906,24175.57031,24295.33984,24384.94922,24356.9707,24451.90039,24411.83984,24402.7793,24365.51953,24195.76953,24036.60938,24169.50977,24238.68945,24200.099609,24162.17969,24161.21094,24032.81055,24107.34961,24044.48047],
    "abs_body":[186.66016,21.720707,2.89844,251.25977,10.25,64.66992,52.84961,44.058591,156.83984,14.74024,202.16016,65.500002,105.16992,89.12891,32.0293,90.08984,41.14063,9.95117,37.71094,164.37109,167.23046,133.26954,66.3789,29.019531,39.78125,2.60937,126.02929,81.01953,58.30859],
    "body":[-186.66016,21.720707,2.89844,251.25977,-10.25,64.66992,-52.84961,-44.058591,-156.83984,14.74024,-202.16016,-65.500002,105.16992,89.12891,-32.0293,90.08984,-41.14063,-9.95117,-37.71094,-164.37109,-167.23046,133.26954,66.3789,-29.019531,-39.78125,-2.60937,-126.02929,81.01953,-58.30859]   
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70097,2023-02-23 09:30:00,24201.960940,24222.730470,24160.029297,24162.17969,NaN,39.781250,-39.781250,NaN,NaN
70098,2023-02-23 10:00:00,24163.820310,24170.320310,24031.099609,24161.21094,NaN,2.609370,-2.609370,NaN,NaN
70099,2023-02-23 10:30:00,24158.839840,24168.150390,24007.919920,24032.81055,NaN,126.029290,-126.029290,NaN,NaN
70100,2023-02-23 11:00:00,24026.330080,24113.029297,24013.310550,24107.34961,NaN,81.019530,81.019530,NaN,NaN
70101,2023-02-23 11:30:00,24102.789060,24128.259770,24028.179690,24044.48047,NaN,58.308590,-58.308590,NaN,NaN

In [20]:
missing_times=pd.date_range(start="2023-03-04 23:00",end="2023-03-05 01:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[22422.019531,22420.60938,22386.86914,22314.14062,22306.85938,22354.26953],
    "high":[22448.36914,22422.050781,22394.24023,22355.99023,22389.84961,22377.71094],
    "low":[22395.92969,22375.25,22263.57031,22294.13086,22301.080078,22333.2207],
    "close":[22417.42969,22394.24023,22316.21094,22311.89062,22356.48047,22355.060547],
    "abs_body":[4.589841,26.36915,70.6582,2.25,49.62109,0.791017],
    "body":[-4.589841,-26.36915,-70.6582,-2.25,49.62109,0.791017]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.769530,46557.179690,46640.531250,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.261720,46075.000000,46080.871090,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.871090,45656.550780,45693.148440,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.808590,45655.429690,46037.410160,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.210940,45823.949220,45881.539060,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70103,2023-03-04 23:30:00,22420.609380,22422.050781,22375.250000,22394.240230,NaN,26.369150,-26.369150,NaN,NaN
70104,2023-03-05 00:00:00,22386.869140,22394.240230,22263.570310,22316.210940,NaN,70.658200,-70.658200,NaN,NaN
70105,2023-03-05 00:30:00,22314.140620,22355.990230,22294.130860,22311.890620,NaN,2.250000,-2.250000,NaN,NaN
70106,2023-03-05 01:00:00,22306.859380,22389.849610,22301.080078,22356.480470,NaN,49.621090,49.621090,NaN,NaN
70107,2023-03-05 01:30:00,22354.269530,22377.710940,22333.220700,22355.060547,NaN,0.791017,0.791017,NaN,NaN

In [21]:
missing_times=pd.date_range(start="2023-07-20 00:00",end="2023-07-20 03:30",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[29929.14,29909.63,29775.01,29720.64,29728.11,29783.77,29830.69,29807.85],
    "high":[29932.4,29946.23,29817.33,29794.65,29818.44,29841.05,29831.53,29823.14],
    "low":[29859.69,29771.55,29685.27,29704.95,29690.39,29756.01,29778.89,29768.22],
    "close":[29910.96,29775,29722.14,29728.11,29783.61,29830.7,29807.88,29790.82],
    "abs_body":[18.18,134.63,52.87,7.47,55.5,46.93,22.81,17.03],
    "body":[-18.18,-134.63,-52.87,7.47,55.5,46.93,-22.81,-17.03]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70111,2023-07-20 01:30:00,29720.640000,29794.65000,29704.95000,29728.11000,NaN,7.470000,7.470000,NaN,NaN
70112,2023-07-20 02:00:00,29728.110000,29818.44000,29690.39000,29783.61000,NaN,55.500000,55.500000,NaN,NaN
70113,2023-07-20 02:30:00,29783.770000,29841.05000,29756.01000,29830.70000,NaN,46.930000,46.930000,NaN,NaN
70114,2023-07-20 03:00:00,29830.690000,29831.53000,29778.89000,29807.88000,NaN,22.810000,-22.810000,NaN,NaN
70115,2023-07-20 03:30:00,29807.850000,29823.14000,29768.22000,29790.82000,NaN,17.030000,-17.030000,NaN,NaN

In [22]:
missing_times=pd.date_range(start="2024-10-26 22:00",end="2024-10-26 22:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[67579.54],
    "high":[67864.16],
    "low":[67512.9],
    "close":[67633.74],
    "abs_body":[54.2],
    "body":[54.2]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70112,2023-07-20 02:00:00,29728.110000,29818.44000,29690.39000,29783.61000,NaN,55.500000,55.500000,NaN,NaN
70113,2023-07-20 02:30:00,29783.770000,29841.05000,29756.01000,29830.70000,NaN,46.930000,46.930000,NaN,NaN
70114,2023-07-20 03:00:00,29830.690000,29831.53000,29778.89000,29807.88000,NaN,22.810000,-22.810000,NaN,NaN
70115,2023-07-20 03:30:00,29807.850000,29823.14000,29768.22000,29790.82000,NaN,17.030000,-17.030000,NaN,NaN
70116,2024-10-26 22:00:00,67579.540000,67864.16000,67512.90000,67633.74000,NaN,54.200000,54.200000,NaN,NaN

In [23]:
missing_times=pd.date_range(start="2025-10-25 21:00",end="2025-10-26 02:00",freq="30min")
missing_df=pd.DataFrame({
    "datetime":missing_times,
    "open":[110608.48,110070.08,110370.87,110282.04,110516.01,110231.46,110528.01,110621.56,110948.65,110624.01,110754],
    "high":[110636.73,110411.24,110378.96,110600,110519.16,110658.51,110654.51,110980.7,110955.64,110817.37,111040.55],
    "low":[109910.01,109804.93,109930,110195.8,110231.47,110165.84,110422,110617.05,110506.46,110485.4,110676.22],
    "close":[110070.09,110374.01,110286.93,110516.01,110233.73,110524.36,110621.56,110948.65,110624.14,110753.99,110920.22],
    "abs_body":[538.39,303.93,83.94,233.97,282.28,292.9,93.55,327.09,324.51,129.98,166.22],
    "body":[-538.39,303.93,-83.94,233.97,-282.28,292.9,93.55,327.09,-324.51,129.98,166.22]
})
data=pd.concat([data,missing_df],ignore_index=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0.0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0.0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0.0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1.0,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0.0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70123,2025-10-26 00:00:00,110528.010000,110654.51000,110422.00000,110621.56000,NaN,93.550000,93.550000,NaN,NaN
70124,2025-10-26 00:30:00,110621.560000,110980.70000,110617.05000,110948.65000,NaN,327.090000,327.090000,NaN,NaN
70125,2025-10-26 01:00:00,110948.650000,110955.64000,110506.46000,110624.14000,NaN,324.510000,-324.510000,NaN,NaN
70126,2025-10-26 01:30:00,110624.010000,110817.37000,110485.40000,110753.99000,NaN,129.980000,129.980000,NaN,NaN
70127,2025-10-26 02:00:00,110754.000000,111040.55000,110676.22000,110920.22000,NaN,166.220000,166.220000,NaN,NaN

In [24]:
data['datetime']=pd.to_datetime(data['datetime'])
data=data.sort_values("datetime").reset_index(drop=True)
data['color']=np.where(data['close']>data['open'],1,0)
data['open']=pd.to_numeric(data['open'])
data['close']=pd.to_numeric(data['close'])
data['abs_body']=abs(data['close']-data['open'])
data['body']=(data['close']-data['open'])
data['high']=pd.to_numeric(data['high'])
data['low']=pd.to_numeric(data['low'])
data['upper_wick']=np.where(data['color']==1,data['high']-data['close'],data['high']-data['open'])
data['lower_wick']=np.where(data['color']==1,data['open']-data['low'],data['close']-data['low'])
data=data.dropna()
data=data.reset_index(drop=True)
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984
...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000

In [26]:
data.to_csv('BTC_22-25.csv',index=False)

In [27]:
data['body_to_range']=data['body']/(data['high']-data['low']+1e-10)
data['upper_wick_ratio']=data['upper_wick']/(data['high']-data['low']+1e-10)
data['lower_wick_ratio']=data['lower_wick']/(data['high']-data['low']+1e-10)
data['price_change']=data['close'].pct_change()
data['price_change_2']=data['close'].pct_change(2)
data['price_change_4']=data['close'].pct_change(4)
data['sma_5']=data['close'].rolling(5).mean()
data['sma_10']=data['close'].rolling(10).mean()
data['sma_20']=data['close'].rolling(20).mean()
data['close_to_sma5']=(data['close']-data['sma_5'])/data['sma_5']
data['close_to_sma10']=(data['close']-data['sma_10'])/data['sma_10']
data['volatility']=data['close'].rolling(10).std()
data['volume']=pd.to_numeric(data['volume'])
data['taker_volume']=pd.to_numeric(data['taker_volume'])
data['no_of_trades']=pd.to_numeric(data['no_of_trades'])
data['taker_buy_ratio']=data['taker_volume']/data['volume']
data['avg_trade_size']=data['volume']/data['no_of_trades']
data['vol_z']=(data['volume']-data['volume'].rolling(48).mean().shift(1))/data['volume'].rolling(48).std().shift(1)
delta=data['close'].diff()
gain=delta.where(delta>0,0).rolling(14).mean()
loss=delta.where(delta<0,0).rolling(14).mean()
rs=gain/(loss+1e-10)
data['rsi']=100-(100/(1+rs))
data

KeyError: 'volume'

In [ ]:
df_volume=[]
df_takervolume=[]
df_opentime=[]
df_trades=[]
interval='30m'
for yr in range(2022,2026):
    for m in range(1,13):  
        start_date=f'{yr}-{(m):02d}-01'
        end_date=f'{yr}-{(m):02d}-16'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api1.binance.com/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(0.1)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
        last_day=calendar.monthrange(yr,m)[1]
        start_date=f'{yr}-{(m):02d}-16'
        end_date=f'{yr}-{(m):02d}-{(last_day)}'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api1.binance.com/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(0.1)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
df_binance=pd.DataFrame({
    'open_time':pd.to_datetime(df_opentime,unit='ms'),
    'volume':df_volume,
    'taker_volume':df_takervolume,
    'no_of_trades':df_trades
}).dropna()
df_binance['open_time']=df_binance['open_time'].dt.tz_localize('UTC').dt.tz_convert('Asia/Kolkata')
df_binance

KeyboardInterrupt:

In [31]:
df_binance=pd.read_csv('binance_22-25.csv')
df_binance

                       open_time        volume  taker_volume  no_of_trades
0      2022-01-01 01:00:00+05:30  1.146748e+08  4.930189e+07       49761.0
1      2022-01-01 01:30:00+05:30  6.113717e+07  3.375046e+07       32543.0
2      2022-01-01 02:00:00+05:30  2.308425e+07  1.213224e+07       18757.0
3      2022-01-01 02:30:00+05:30  4.087805e+07  2.338065e+07       27016.0
4      2022-01-01 03:00:00+05:30  3.909260e+07  2.144366e+07       27563.0
...                          ...           ...           ...           ...
67913  2025-12-30 23:00:00+05:30  4.250846e+07  2.167012e+07      105824.0
67914  2025-12-30 23:30:00+05:30  1.873078e+07  1.009447e+07       72103.0
67915  2025-12-31 00:00:00+05:30  1.963927e+07  9.808946e+06       63776.0
67916  2025-12-31 00:30:00+05:30  2.163632e+07  1.154721e+07       93779.0
67917  2025-12-31 01:00:00+05:30  8.827184e+06  3.978945e+06       52946.0

[67918 rows x 4 columns]

In [ ]:
df_volume=[]
df_takervolume=[]
df_opentime=[]
df_trades=[]
interval='30m'
for yr in range(2022,2026):
    for m in range(1,13):  
        start_date=f'{yr}-{(m):02d}-01'
        end_date=f'{yr}-{(m):02d}-16'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api.binance.us/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(4)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
        last_day=calendar.monthrange(yr,m)[1]
        start_date=f'{yr}-{(m):02d}-16'
        end_date=f'{yr}-{(m):02d}-{(last_day)}'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        api_url=f"https://api.binance.us/api/v3/klines?symbol=BTCUSDT&interval={interval}&startTime={start_ms}&endTime={end_ms}&limit=1000"
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(api_url).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                volume=[float(value[7]) for value in fetch]
                taker_volume=[float(value[10]) for value in fetch]
                trades=[float(value[8]) for value in fetch]
                df_volume.extend(volume)
                df_opentime.extend(open_time) 
                df_takervolume.extend(taker_volume)
                df_trades.extend(trades)
                time.sleep(4)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
df_binance_us=pd.DataFrame({
    'open_time':pd.to_datetime(df_opentime,unit='ms'),
    'volume':df_volume,
    'taker_volume':df_takervolume,
    'no_of_trades':df_trades
}).dropna()
df_binance_us

                open_time         volume   taker_volume  no_of_trades
0     2021-12-31 18:30:00  572264.307032  203225.184247         437.0
1     2021-12-31 19:00:00  301496.829618   83181.409841         417.0
2     2021-12-31 19:30:00  615602.921618  199228.184430         730.0
3     2021-12-31 20:00:00  216556.287960  103503.083555         396.0
4     2021-12-31 20:30:00  138782.233532   89600.566910         165.0
...                   ...            ...            ...           ...
67901 2025-12-30 16:30:00   25348.212282   10870.252555          32.0
67902 2025-12-30 17:00:00    6766.208392    4418.856334          30.0
67903 2025-12-30 17:30:00   20592.455223    5319.637185          33.0
67904 2025-12-30 18:00:00    6741.298956    6736.007747          23.0
67905 2025-12-30 18:30:00   15448.766523    1034.827058          29.0

[67906 rows x 4 columns]

In [ ]:
df_volume=[]
df_opentime=[]
for yr in range(2022,2026):
    for m in range(1,13):  
        start_date=f'{yr}-{(m):02d}-01'
        end_date=f'{yr}-{(m):02d}-11'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        url="https://api.exchange.coinbase.com/products/BTC-USD/candles"
        params={
            "granularity":3600,
            "start":f'{start_date}T00:00:00Z',
            "end":f"{end_date}T00:00:00Z"
        }
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(url,params=params).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                close=[float(value[4]) for value in fetch]
                volume_btc=[float(value[5]) for value in fetch]
                volume_usd=[c*v for c,v in zip(close,volume_btc)]
                df_volume.extend(volume_usd)
                df_opentime.extend(open_time) 
                time.sleep(0.1)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
        start_date=f'{yr}-{(m):02d}-11'
        end_date=f'{yr}-{(m):02d}-21'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        url="https://api.exchange.coinbase.com/products/BTC-USD/candles"
        params={
            "granularity":3600,
            "start":f'{start_date}T00:00:00Z',
            "end":f"{end_date}T00:00:00Z"
        }
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(url,params=params).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                close=[float(value[4]) for value in fetch]
                volume_btc=[float(value[5]) for value in fetch]
                volume_usd=[c*v for c,v in zip(close,volume_btc)]
                df_volume.extend(volume_usd)
                df_opentime.extend(open_time) 
                time.sleep(0.1)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
        last_day=calendar.monthrange(yr,m)[1]
        start_date=f'{yr}-{(m):02d}-21'
        end_date=f'{yr}-{(m):02d}-{(last_day)}'
        start_ms=int(time.mktime(time.strptime(start_date,"%Y-%m-%d")))*1000
        end_ms=int(time.mktime(time.strptime(end_date,"%Y-%m-%d")))*1000
        url="https://api.exchange.coinbase.com/products/BTC-USD/candles"
        params={
            "granularity":3600,
            "start":f'{start_date}T00:00:00Z',
            "end":f"{end_date}T00:00:00Z"
        }
        while True:
            session=requests.Session()
            retries=Retry(total=5,backoff_factor=1,status_forcelist=[429,500,502,503,504])
            session.mount("https://",HTTPAdapter(max_retries=retries))
            fetch=session.get(url,params=params).json()
            if fetch:
                open_time=[value[0] for value in fetch]
                close=[float(value[4]) for value in fetch]
                volume_btc=[float(value[5]) for value in fetch]
                volume_usd=[c*v for c,v in zip(close,volume_btc)]
                df_volume.extend(volume_usd)
                df_opentime.extend(open_time) 
                time.sleep(0.1)
                break
            else: 
                print("API Error:",fetch)
                fetch=None
                break
df_coinbase=pd.DataFrame({
    'open_time':pd.to_datetime(df_opentime,unit='s'),
    'volume':df_volume,
}).dropna()
df_coinbase=df_coinbase.sort_values(by='open_time')
df_coinbase.set_index('open_time',inplace=True)
df_coinbase

                           volume
open_time
2022-01-01 00:00:00  3.836669e+07
2022-01-01 01:00:00  3.209512e+07
2022-01-01 02:00:00  2.028560e+07
2022-01-01 03:00:00  1.658006e+07
2022-01-01 04:00:00  2.313707e+07
...                           ...
2025-12-30 20:00:00  3.947508e+07
2025-12-30 21:00:00  2.333742e+07
2025-12-30 22:00:00  1.382648e+07
2025-12-30 23:00:00  1.845918e+07
2025-12-31 00:00:00  1.513813e+07

[34048 rows x 1 columns]

In [ ]:
df_coinbase=df_coinbase.reset_index()
df_coinbase.columns

Index(['index', 'open_time', 'volume'], dtype='object')

In [ ]:
df_coinbase=df_coinbase.set_index('open_time')
df_coinbase=df_coinbase[~df_coinbase.index.duplicated(keep='first')]
df_coinbase_unsampled=df_coinbase.resample('30min').asfreq()
df_coinbase=df_coinbase_unsampled.ffill() 
df_coinbase['volume']=df_coinbase['volume']/2
df_coinbase

                       index        volume
open_time
2022-01-01 00:00:00      0.0  1.918334e+07
2022-01-01 00:30:00      0.0  1.918334e+07
2022-01-01 01:00:00      1.0  1.604756e+07
2022-01-01 01:30:00      1.0  1.604756e+07
2022-01-01 02:00:00      2.0  1.014280e+07
...                      ...           ...
2025-12-30 22:00:00  34045.0  6.913241e+06
2025-12-30 22:30:00  34045.0  6.913241e+06
2025-12-30 23:00:00  34046.0  9.229590e+06
2025-12-30 23:30:00  34046.0  9.229590e+06
2025-12-31 00:00:00  34047.0  7.569063e+06

[70081 rows x 2 columns]

In [ ]:
df_binance

,open_time,volume,taker_volume,no_of_trades
1970-01-01 00:00:00,2021-12-31 18:30:00,5.741317e+07,2.218630e+07,33022.0
1970-01-01 00:00:01,2021-12-31 19:00:00,6.294230e+07,2.873560e+07,37711.0
1970-01-01 00:00:02,2021-12-31 19:30:00,1.146748e+08,4.930189e+07,49761.0
1970-01-01 00:00:03,2021-12-31 20:00:00,6.113717e+07,3.375046e+07,32543.0
1970-01-01 00:00:04,2021-12-31 20:30:00,2.308425e+07,1.213224e+07,18757.0
...,...,...,...,...
1970-01-01 18:51:53,2025-12-30 16:30:00,4.550781e+07,1.735067e+07,145135.0
1970-01-01 18:51:54,2025-12-30 17:00:00,2.063476e+07,1.072612e+07,102346.0
1970-01-01 18:51:55,2025-12-30 17:30:00,4.250846e+07,2.167012e+07,105824.0
1970-01-01 18:51:56,2025-12-30 18:00:00,1.873078e+07,1.009447e+07,72103.0
1970-01-01 18:51:57,2025-12-30 18:30:00,1.963927e+07,9.808946e+06,63776.0

In [33]:
merged_data=pd.merge_asof(data,df_binance,left_index=True,right_index=True,direction='nearest',tolerance=60)
# merged_data=pd.merge_asof(merged_data,df_binance_us,left_index=True,right_index=True,direction='nearest',tolerance=60)
merged_data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,...,sma_5,sma_10,sma_20,close_to_sma5,close_to_sma10,volatility,open_time,volume,taker_volume,no_of_trades
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 01:00:00+05:30,1.146748e+08,4.930189e+07,49761.0
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 01:30:00+05:30,6.113717e+07,3.375046e+07,32543.0
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 02:00:00+05:30,2.308425e+07,1.213224e+07,18757.0
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01 02:30:00+05:30,4.087805e+07,2.338065e+07,27016.0
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,...,46066.700,NaN,NaN,-0.004019,NaN,NaN,2022-01-01 03:00:00+05:30,3.909260e+07,2.144366e+07,27563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,...,88146.172,88476.573,88511.7760,-0.004012,-0.007731,469.110970,NaN,NaN,NaN,NaN
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,...,87882.288,88339.050,88468.1380,-0.003997,-0.009146,527.130418,NaN,NaN,NaN,NaN
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,...,87704.942,88205.011,88421.6865,-0.002380,-0.008035,556.165103,NaN,NaN,NaN,NaN
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,...,87629.122,88086.607,88370.8855,-0.001611,-0.006796,571.524758,NaN,NaN,NaN,NaN
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,...,87624.428,87994.039,88334.5010,0.002167,-0.002042,527.180749,NaN,NaN,NaN,NaN

In [ ]:
merged_data['volume']

datetime
2022-01-01 00:00:00   NaN
2022-01-01 00:30:00   NaN
2022-01-01 01:00:00   NaN
2022-01-01 01:30:00   NaN
2022-01-01 02:00:00   NaN
                       ..
2025-12-31 21:30:00   NaN
2025-12-31 22:00:00   NaN
2025-12-31 22:30:00   NaN
2025-12-31 23:00:00   NaN
2025-12-31 23:30:00   NaN
Name: volume, Length: 70128, dtype: float64

In [ ]:
merged_data['no_of_trades_x'].isna().sum()

2162

In [ ]:
merged_data['vol_z']=(merged_data['volume']-merged_data['volume'].rolling(48).mean())/merged_data['volume'].rolling(48).std()

In [34]:
merged_data['volume']=merged_data['volume_x']+merged_data['volume_y']
merged_data['taker_volume']=merged_data['taker_volume_x']+merged_data['taker_volume_y']
merged_data['no_of_trades']=merged_data['no_of_trades_x']+merged_data['no_of_trades_y']
merged_data['vol_z']=(merged_data['volume']-merged_data['volume'].rolling(48).mean())/merged_data['volume'].rolling(48).std()
merged_data.drop(columns=['volume_x','volume_y','taker_volume_x','taker_volume_y','no_of_trades_x','no_of_trades_y'],inplace=True)
merged_data

KeyError: 'volume_x'

In [35]:
merged_data['volume']=pd.to_numeric(merged_data['volume'])
merged_data['taker_volume']=pd.to_numeric(merged_data['taker_volume'])
merged_data['no_of_trades']=pd.to_numeric(merged_data['no_of_trades'])
merged_data['taker_buy_ratio']=merged_data['taker_volume']/merged_data['volume']
merged_data['avg_trade_size']=merged_data['volume']/merged_data['no_of_trades']
merged_data['vol_z']=(merged_data['volume']-merged_data['volume'].rolling(48).mean())/merged_data['volume'].rolling(48).std()

In [ ]:
merged_data['volume'].isna().sum()

70128

In [ ]:
merged_data['volume']

datetime
2022-01-01 00:00:00   NaN
2022-01-01 00:30:00   NaN
2022-01-01 01:00:00   NaN
2022-01-01 01:30:00   NaN
2022-01-01 02:00:00   NaN
                       ..
2025-12-31 21:30:00   NaN
2025-12-31 22:00:00   NaN
2025-12-31 22:30:00   NaN
2025-12-31 23:00:00   NaN
2025-12-31 23:30:00   NaN
Name: volume, Length: 70128, dtype: float64

In [36]:
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,...,lower_wick_ratio,price_change,price_change_2,price_change_4,sma_5,sma_10,sma_20,close_to_sma5,close_to_sma10,volatility
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,...,0.211236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,...,0.010101,-0.011999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,...,0.055257,-0.008414,-0.020312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,...,0.030165,0.007534,-0.000943,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,...,0.197725,-0.003386,0.004123,-0.016273,46066.700,NaN,NaN,-0.004019,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,...,0.626854,-0.000515,-0.000848,-0.011907,88146.172,88476.573,88511.7760,-0.004012,-0.007731,469.110970
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,...,0.491056,-0.002978,-0.003492,-0.009639,87882.288,88339.050,88468.1380,-0.003997,-0.009146,527.130418
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,...,0.496805,-0.000398,-0.003375,-0.004220,87704.942,88205.011,88421.6865,-0.002380,-0.008035,556.165103
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,...,0.582966,-0.000095,-0.000492,-0.003983,87629.122,88086.607,88370.8855,-0.001611,-0.006796,571.524758
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,...,0.126625,0.003730,0.003635,0.000248,87624.428,87994.039,88334.5010,0.002167,-0.002042,527.180749

In [ ]:
merged_data.index=pd.to_datetime(data['datetime'],unit='s')
merged_data.index

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 00:30:00',
               '2022-01-01 01:00:00', '2022-01-01 01:30:00',
               '2022-01-01 02:00:00', '2022-01-01 02:30:00',
               '2022-01-01 03:00:00', '2022-01-01 03:30:00',
               '2022-01-01 04:00:00', '2022-01-01 04:30:00',
               ...
               '2025-12-31 19:00:00', '2025-12-31 19:30:00',
               '2025-12-31 20:00:00', '2025-12-31 20:30:00',
               '2025-12-31 21:00:00', '2025-12-31 21:30:00',
               '2025-12-31 22:00:00', '2025-12-31 22:30:00',
               '2025-12-31 23:00:00', '2025-12-31 23:30:00'],
              dtype='datetime64[ns]', name='datetime', length=70128, freq=None)

In [ ]:
merged_data=pd.merge_asof(merged_data,df_coinbase,left_index=True,right_index=True,direction='nearest',tolerance=pd.Timedelta('90s'))
merged_data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,volume_x,taker_volume,no_of_trades,taker_buy_ratio,avg_trade_size,vol_z,index,volume_y
datetime,,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,5.798544e+07,2.238953e+07,33459.0,0.386123,1733.029599,NaN,0.0,1.918334e+07
2022-01-01 00:30:00,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,6.324380e+07,2.881878e+07,38128.0,0.455678,1658.723170,NaN,0.0,1.918334e+07
2022-01-01 01:00:00,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,1.152904e+08,4.950112e+07,50491.0,0.429360,2283.384785,NaN,1.0,1.604756e+07
2022-01-01 01:30:00,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,6.135372e+07,3.385396e+07,32939.0,0.551783,1862.646777,NaN,1.0,1.604756e+07
2022-01-01 02:00:00,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,2.322303e+07,1.222184e+07,18922.0,0.526281,1227.303218,NaN,2.0,1.014280e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 21:30:00,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 22:00:00,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 22:30:00,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 23:00:00,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 23:30:00,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged_data['volume']=merged_data['volume_x']+merged_data['volume_y']
merged_data.drop(columns=['volume_x','volume_y'],inplace=True)
merged_data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,taker_volume,no_of_trades,taker_buy_ratio,avg_trade_size,vol_z,index,volume
datetime,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,2.238953e+07,33459.0,0.386123,1733.029599,NaN,0.0,7.716878e+07
2022-01-01 00:30:00,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,2.881878e+07,38128.0,0.455678,1658.723170,NaN,0.0,8.242714e+07
2022-01-01 01:00:00,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,4.950112e+07,50491.0,0.429360,2283.384785,NaN,1.0,1.313379e+08
2022-01-01 01:30:00,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,3.385396e+07,32939.0,0.551783,1862.646777,NaN,1.0,7.740128e+07
2022-01-01 02:00:00,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,1.222184e+07,18922.0,0.526281,1227.303218,NaN,2.0,3.336583e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 21:30:00,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 22:00:00,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 22:30:00,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 23:00:00,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31 23:30:00,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged_data['volume'].mean()

67530803.6307887

In [40]:
data['vol_z'].isna().sum()

2211

In [37]:
data=merged_data
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,...,close_to_sma5,close_to_sma10,volatility,open_time,volume,taker_volume,no_of_trades,taker_buy_ratio,avg_trade_size,vol_z
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,...,NaN,NaN,NaN,2022-01-01 01:00:00+05:30,1.146748e+08,4.930189e+07,49761.0,0.429928,2304.511128,NaN
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,...,NaN,NaN,NaN,2022-01-01 01:30:00+05:30,6.113717e+07,3.375046e+07,32543.0,0.552045,1878.657957,NaN
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,...,NaN,NaN,NaN,2022-01-01 02:00:00+05:30,2.308425e+07,1.213224e+07,18757.0,0.525563,1230.700499,NaN
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,...,NaN,NaN,NaN,2022-01-01 02:30:00+05:30,4.087805e+07,2.338065e+07,27016.0,0.571961,1513.105294,NaN
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,...,-0.004019,NaN,NaN,2022-01-01 03:00:00+05:30,3.909260e+07,2.144366e+07,27563.0,0.548535,1418.299959,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,...,-0.004012,-0.007731,469.110970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,...,-0.003997,-0.009146,527.130418,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,...,-0.002380,-0.008035,556.165103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,...,-0.001611,-0.006796,571.524758,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,...,0.002167,-0.002042,527.180749,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
data=merged_data
count1=0
count2=0
count3=0
for i in range(5,len(data)-10):
    window=data.iloc[i-5:i+1]
    if data['vol_z'][i]>2.1:
        count1+=1
        if data['taker_buy_ratio'][i]>0.6:
            count2+=1
            if data['avg_trade_size'][i]>1700:
                count3+=1
print(count1,count2,count3)

3807 329 44

In [41]:
count1=0
count2=0
count3=0
for i in range(5,len(data)-10):
    window=data.iloc[i-5:i+1]
    if data['vol_z'][i]>2.1:
        count1+=1
    if data['taker_buy_ratio'][i]>0.6:
        count2+=1
    if data['avg_trade_size'][i]>1700:
        count3+=1
print(count1,count2,count3)

3807 3860 4077

In [42]:
data['vol_z'].mean()

0.011261799759071428

In [43]:
bear_rev=0
bull_rev=0
bear_cont=0
bull_cont=0
bear_rev_ret=0
bull_rev_ret=0
bear_cont_ret=0
bull_cont_ret=0
shooting_star=0
bearish_engulfing=0
advance_block=0
hanging_man=0
tweezer_top=0
evening_star=0
hammer=0
inverted_hammer=0
bullish_engulfing=0
three_stars_in_the_south=0
tweezer_bottom=0
morning_star=0
bearish_three_line_strike=0
falling_three_methods=0
bearish_mat_hold=0
bullish_three_line_strike=0
rising_three_methods=0
bullish_mat_hold=0
shooting_star_ret=0
bearish_engulfing_ret=0
advance_block_ret=0
hanging_man_ret=0
tweezer_top_ret=0
evening_star_ret=0
hammer_ret=0
inverted_hammer_ret=0
bullish_engulfing_ret=0
three_stars_in_the_south_ret=0
tweezer_bottom_ret=0
morning_star_ret=0
bearish_three_line_strike_ret=0
falling_three_methods_ret=0
bearish_mat_hold_ret=0
bullish_three_line_strike_ret=0
rising_three_methods_ret=0
bullish_mat_hold_ret=0

In [ ]:
data=merged_data
tweezer=[]
for i in range(5,len(data)-10):
    ret=0
    # if data['vol_z'][i]<1:
    #     continue
    # if data['taker_buy_ratio'][i]<0.6:
    #     continue 
    # if data['avg_trade_size'][i]<1000:
    #     continue
    window=data.iloc[i-5:i+1]
    pattern1=bearish_reversal(window)
    pattern2=bullish_reversal(window)
    pattern3=bearish_continuation(window)
    pattern4=bullish_continuation(window)
    if pattern1:
        bear_rev+=1
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        bear_rev_ret+=ret
        if pattern1==1:
            shooting_star_ret+=ret
        elif pattern1==2:
            bearish_engulfing_ret+=ret
        elif pattern1==3:
            advance_block_ret+=ret
        elif pattern1==4:
            hanging_man_ret+=ret
        elif pattern1==5:
            tweezer_top_ret+=ret
        elif pattern1==6:
            evening_star_ret+=ret
    if pattern2:
        bull_rev+=1
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        bull_rev_ret+=ret
        if pattern2==1:
            hammer_ret+=ret
        elif pattern2==2:
            inverted_hammer_ret+=ret
        elif pattern2==3:
            bullish_engulfing_ret+=ret
        elif pattern2==4:
            three_stars_in_the_south_ret+=ret
        elif pattern2==5:
            tweezer_bottom_ret+=ret
        elif pattern2==6:
            morning_star_ret+=ret
    if pattern3:
        bear_cont+=1
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        bear_cont_ret+=ret
        if pattern3==1:
            bearish_three_line_strike_ret+=ret
        elif pattern3==2:
            falling_three_methods_ret+=ret
        elif pattern3==3:
            bearish_mat_hold_ret+=ret
    if pattern4:
        bull_cont+=1
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        bull_cont_ret+=ret
        if pattern4==1:
            bullish_three_line_strike_ret+=ret
        elif pattern4==2:
            rising_three_methods_ret+=ret
        elif pattern4==3:
            bullish_mat_hold_ret+=ret

In [ ]:
bear_rev,bull_rev,bear_cont,bull_cont

(20499, 10176, 368, 430)

In [ ]:
bear_rev+bull_rev+bear_cont+bull_cont

25571

In [44]:
def bearish_reversal(data):
    global shooting_star,bearish_engulfing,advance_block,hanging_man,tweezer_top,evening_star
    if data["close"].iloc[-2]<data["close"].iloc[-1]:  # Shooting Star
        if data["color"].iloc[-1]==0: 
            if data["upper_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
                if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
                    return 1
    if data["color"].iloc[-2]==1:  # Bearish Engulfing 
        if data["color"].iloc[-1]==0:
            if data["abs_body"].iloc[-1]>data["abs_body"].iloc[-2]:
                    return 2
    if all(data["color"].iloc[-3:]==1):  # Advance Block
        if data["body"].iloc[-3]>data["body"].iloc[-2]:
            if data["body"].iloc[-2]>data["body"].iloc[-1]:
                if data["upper_wick"].iloc[-2]>data["upper_wick"].iloc[-3]:
                    if data["upper_wick"].iloc[-1]>data["upper_wick"].iloc[-3]:
                        if data["upper_wick"].iloc[-1]>data["upper_wick"].iloc[-2]:
                            return 3
    if data["color"].iloc[-1]==0:  # Hanging Man
        if data["lower_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
            if data["upper_wick"].iloc[-1]<0.1*data["lower_wick"].iloc[-1]:
                return 4
    if data["close"].iloc[-3]<data["close"].iloc[-2]:  # Tweezer Top
        if data["color"].iloc[-1]==0:
            if data["color"].iloc[-2]==1:
                if 0.99*data["high"].iloc[-1]<data["high"].iloc[-2]<1.01*data["high"].iloc[-1]:  
                    return 5 
    if data["color"].iloc[-3]==1:  # Evening Star
        if data["color"].iloc[-1]==0:
            if data["upper_wick"].iloc[-3]+data["lower_wick"].iloc[-3]<data["abs_body"].iloc[-3]:
                if data["upper_wick"].iloc[-1]+data["lower_wick"].iloc[-1]<data["abs_body"].iloc[-1]:
                    if data["abs_body"].iloc[-2]<0.2*(data["high"].iloc[-2]-data["low"].iloc[-2]):
                        if data["close"].iloc[-1]<(data["open"].iloc[-3]+data["close"].iloc[-3])/2:
                            return 6
    return 0

In [45]:
data['price_change']=data['close'].pct_change()
data['price_change_2']=data['close'].pct_change(2)
data['price_change_4']=data['close'].pct_change(4)
data['sma_5']=data['close'].rolling(5).mean()
data['sma_10']=data['close'].rolling(10).mean()
data['sma_20']=data['close'].rolling(20).mean()
data['close_to_sma5']=(data['close']-data['sma_5'])/data['sma_5']
data['close_to_sma10']=(data['close']-data['sma_10'])/data['sma_10']
data['volatility']=data['close'].rolling(10).std()
data

,datetime,open,high,low,close,color,abs_body,body,upper_wick,lower_wick,...,close_to_sma5,close_to_sma10,volatility,open_time,volume,taker_volume,no_of_trades,taker_buy_ratio,avg_trade_size,vol_z
0,2022-01-01 00:00:00,46894.300780,46951.76953,46557.17969,46640.53125,0,253.769530,-253.769530,57.468750,83.35156,...,NaN,NaN,NaN,2022-01-01 01:00:00+05:30,1.146748e+08,4.930189e+07,49761.0,0.429928,2304.511128,NaN
1,2022-01-01 00:30:00,46656.261720,46656.26172,46075.00000,46080.87109,0,575.390630,-575.390630,0.000000,5.87109,...,NaN,NaN,NaN,2022-01-01 01:30:00+05:30,6.113717e+07,3.375046e+07,32543.0,0.552045,1878.657957,NaN
2,2022-01-01 01:00:00,46064.070312,46318.87109,45656.55078,45693.14844,0,370.921872,-370.921872,254.800778,36.59766,...,NaN,NaN,NaN,2022-01-01 02:00:00+05:30,2.308425e+07,1.213224e+07,18757.0,0.525563,1230.700499,NaN
3,2022-01-01 01:30:00,45671.730470,46195.80859,45655.42969,46037.41016,1,365.679690,365.679690,158.398430,16.30078,...,NaN,NaN,NaN,2022-01-01 02:30:00+05:30,4.087805e+07,2.338065e+07,27016.0,0.571961,1513.105294,NaN
4,2022-01-01 02:00:00,46042.019531,46115.21094,45823.94922,45881.53906,0,160.480471,-160.480471,73.191409,57.58984,...,-0.004019,NaN,NaN,2022-01-01 03:00:00+05:30,3.909260e+07,2.144366e+07,27563.0,0.548535,1418.299959,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70123,2025-12-31 21:30:00,87830.030000,87932.17000,87558.00000,87792.55000,0,37.480000,-37.480000,102.140000,234.55000,...,-0.004012,-0.007731,469.110970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70124,2025-12-31 22:00:00,87797.910000,87813.02000,87259.01000,87531.06000,0,266.850000,-266.850000,15.110000,272.05000,...,-0.003997,-0.009146,527.130418,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70125,2025-12-31 22:30:00,87531.060000,87637.99000,87356.29000,87496.24000,0,34.820000,-34.820000,106.930000,139.95000,...,-0.002380,-0.008035,556.165103,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70126,2025-12-31 23:00:00,87496.250000,87550.34000,87400.76000,87487.96000,0,8.290000,-8.290000,54.090000,87.20000,...,-0.001611,-0.006796,571.524758,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70127,2025-12-31 23:30:00,87487.960000,87866.97000,87433.01000,87814.33000,1,326.370000,326.370000,52.640000,54.95000,...,0.002167,-0.002042,527.180749,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
data["close_to_sma5"].mean()

2.138834804598496e-05

In [85]:
bear_rev=0
bear_rev_ret=0
shooting_star=0
bearish_engulfing=0
advance_block=0
hanging_man=0
tweezer_top=0
evening_star=0
shooting_star_ret=0
bearish_engulfing_ret=0
advance_block_ret=0
hanging_man_ret=0
tweezer_top_ret=0
evening_star_ret=0

In [777]:
data['taker_buy_ratio'].min()

0.10696070359369877

In [ ]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<1.5:
    #     continue
    # if data['taker_buy_ratio'][i]<0.49:
    #     continue
    # if data['avg_trade_size'][i]<1200:
    #     continue
    # if data['price_change_4'][i]<3.73e-04:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-04:
    #     continue
    ret=0
    window=data.iloc[i-5:i+1]
    pattern1=bearish_reversal(window)
    if pattern1:
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        if pattern1==1: 
            shooting_star+=1
            shooting_star_ret+=ret
            bear_rev+=1
            bear_rev_ret+=ret
        if pattern1==2:
            if data['close_to_sma5'][i]>9.18e-05:
                bearish_engulfing+=1
                bearish_engulfing_ret+=ret
                bear_rev+=1
                bear_rev_ret+=ret
        if pattern1==3:
            advance_block+=1
            advance_block_ret+=ret
            bear_rev+=1
            bear_rev_ret+=ret
        if pattern1==4:
            hanging_man+=1
            hanging_man_ret+=ret
            bear_rev+=1
            bear_rev_ret+=ret
        if pattern1==5:
            if data['vol_z'][i]>1.5:
                tweezer_top+=1
                tweezer_top_ret+=ret
                bear_rev+=1
                bear_rev_ret+=ret
        if pattern1==6:
            evening_star+=1
            evening_star_ret+=ret
            bear_rev+=1
            bear_rev_ret+=ret
    else:
        continue

In [88]:
print(shooting_star,bearish_engulfing,advance_block,hanging_man,tweezer_top,evening_star)

0 0 0 0 1028 0

In [89]:
tweezer_top_ret/tweezer_top

6.817000948054659

In [51]:
print(shooting_star_ret/shooting_star,bearish_engulfing_ret/bearish_engulfing,advance_block_ret/advance_block,hanging_man_ret/hanging_man,
tweezer_top_ret/tweezer_top,evening_star_ret/evening_star)

8.896543195122543 6.420547562530662 44.92895466231336 23.976953621413127 -5.760943512323995 47.81498254516143

In [2439]:
bear_rev

5768

In [1521]:
bear_rev_ret/bear_rev

11.615311757697697

In [ ]:
print(hammer_ret/hammer,inverted_hammer_ret/inverted_hammer,bullish_engulfing_ret/bullish_engulfing,three_stars_in_the_south_ret/three_stars_in_the_south,
tweezer_bottom_ret/tweezer_bottom,morning_star_ret/morning_star)

-12.9544827641381 19.907282980829944 9.873166824305635 -7.9873949320298 33.73588213444846 -25.96234587845318

In [ ]:
print(bearish_three_line_strike_ret/bearish_three_line_strike,falling_three_methods_ret/falling_three_methods,
bearish_mat_hold_ret/(bearish_mat_hold+1e-8))

-15.194933089149622 -166.54081947692345 355.5507764444973

In [ ]:
print(bullish_three_line_strike_ret/bullish_three_line_strike,rising_three_methods_ret/rising_three_methods,bullish_mat_hold_ret/(bullish_mat_hold+1e-8))

-6.1370714375319775 67.41831385365846 0.0

In [ ]:
# for i in range(5,len(data)-10):
#     ret=0
#     window=data.iloc[i-5:i+1]
#     pattern1=bearish_reversal(window)
#     if pattern1:
#         ret=data['close'].iloc[i]-data['close'].iloc[i+4]
#         if pattern1==1:
#             if data['vol_z'][i]>0 and data['taker_buy_ratio'][i]>0.5 and data['avg_trade_size'][i]>800:  
#                 shooting_star+=1
#                 shooting_star_ret+=ret
#                 bear_rev+=1
#                 bear_rev_ret+=ret
        # if pattern1==2:
        #     if data['price_change_4'][i]>3.73e-03 and data['close_to_sma10'][i]>5.66e-03:
        #         bearish_engulfing+=1
        #         bearish_engulfing_ret+=ret
        #         bear_rev+=1
        #         bear_rev_ret+=ret
        # if pattern1==3:
        #     if data['price_change_4'][i]>3.73e-05 and data['close_to_sma10'][i]>5.66e-05:
        # if data["close"].iloc[-6]<data["close"].iloc[-5]<data["close"].iloc[-4]: 
        #         advance_block+=1
        #         advance_block_ret+=ret
        #         bear_rev+=1
        #         bear_rev_ret+=ret
        # if pattern1==4:
        #     hanging_man+=1
        #     hanging_man_ret+=ret
        #     bear_rev+=1
        #     bear_rev_ret+=ret
        # if pattern1==5:
        #     if data['vol_z'][i]>0.5:
        #         tweezer_top+=1
        #         tweezer_top_ret+=ret
        #         bear_rev+=1
        #         bear_rev_ret+=ret
        # if pattern1==6:
        # if data["close"].iloc[-5]<data["close"].iloc[-4]<data["close"].iloc[-3]: 
        #     evening_star+=1
        #     evening_star_ret+=ret
        #     bear_rev+=1
        #     bear_rev_ret+=ret
    # else:
    #     continue

In [90]:
def bullish_reversal(data):
    global hammer,inverted_hammer,bullish_engulfing,three_stars_in_the_south,tweezer_bottom,morning_star
    # if data["color"].iloc[-1]==1:  # Hammer
    if data["lower_wick"].iloc[-1]>2*data["body"].iloc[-1]:
            if data["upper_wick"].iloc[-1]<0.2*data["lower_wick"].iloc[-1]:
                return 1
    if data["upper_wick"].iloc[-1]>2*data["body"].iloc[-1]:  # Inverted Hammer
        if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
            return 2
    if data["color"].iloc[-2]==0:  # Bullish Engulfing
        if data["abs_body"].iloc[-2]>data["upper_wick"].iloc[-2]:
            if data["abs_body"].iloc[-2]>data["lower_wick"].iloc[-2]:
                if data["color"].iloc[-1]==1:
                    if data["body"].iloc[-1]>data["upper_wick"].iloc[-1]:
                        if data["body"].iloc[-1]>data["lower_wick"].iloc[-1]:
                            if data["body"].iloc[-1]>data["body"].iloc[-2]:
                                return 3
    if data["close"].iloc[-5]>data["close"].iloc[-4]>data["close"].iloc[-3]>data["close"].iloc[-2]>data["close"].iloc[-1]:  # Three Stars in the South
        if all(data["color"].iloc[-3:]==0): 
            return 4
    if data["color"].iloc[-1]==1:  # Tweezer Bottom
        if data["color"].iloc[-2]==0:
            if data["abs_body"].iloc[-1]>data["abs_body"].iloc[-2]:
                if 0.9*data["lower_wick"].iloc[-1]<data["lower_wick"].iloc[-2]<1.1*data["lower_wick"].iloc[-1]:
                    return 5
    if data["color"].iloc[-3]==0:  # Morning Star
        if data["color"].iloc[-1]==1:
            if data["abs_body"].iloc[-2]<0.1*data["abs_body"].iloc[-1]:
                if data["abs_body"].iloc[-2]<0.1*data["abs_body"].iloc[-3]:
                    return 6
    return 0

In [203]:
bull_rev=0
bull_rev_ret=0
hammer=0
inverted_hammer=0
bullish_engulfing=0
three_stars_in_the_south=0
tweezer_bottom=0
morning_star=0
hammer_ret=0
inverted_hammer_ret=0
bullish_engulfing_ret=0
three_stars_in_the_south_ret=0
tweezer_bottom_ret=0
morning_star_ret=0

In [204]:
for i in range(5,len(data)-10):
    ret=0
    window=data.iloc[i-5:i+1]
    pattern2=bullish_reversal(window)
    if pattern2:
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        if pattern2==1:  
            if data['avg_trade_size'][i]>900:
                hammer+=1
                hammer_ret+=ret
                bull_rev+=1
                bull_rev_ret+=ret
        if pattern2==2:
            inverted_hammer+=1
            inverted_hammer_ret+=ret
            bull_rev+=1
            bull_rev_ret+=ret
        if pattern2==3:
            bullish_engulfing+=1
            bullish_engulfing_ret+=ret
            bull_rev+=1
            bull_rev_ret+=ret
        if pattern2==4:
            three_stars_in_the_south+=1
            three_stars_in_the_south_ret+=ret
            bull_rev+=1
            bull_rev_ret+=ret
        if pattern2==5:
            tweezer_bottom+=1
            tweezer_bottom_ret+=ret
            bull_rev+=1
            bull_rev_ret+=ret
        if pattern2==6:
            if data['vol_z'][i]>0.45:
                morning_star+=1
                morning_star_ret+=ret
                bull_rev+=1
                bull_rev_ret+=ret
    else:
        continue

In [205]:
print(hammer,inverted_hammer,bullish_engulfing,three_stars_in_the_south,tweezer_bottom,morning_star)

4076 6327 5600 1899 299 121

In [206]:
print(hammer_ret/hammer,inverted_hammer_ret/inverted_hammer,bullish_engulfing_ret/bullish_engulfing,three_stars_in_the_south_ret/three_stars_in_the_south,
tweezer_bottom_ret/tweezer_bottom,morning_star_ret/morning_star)

1.4476833394014064 15.372089247431665 9.182148096982111 2.774725678778345 40.740828054180874 7.1827243504131495

In [1744]:
bull_rev_ret/bull_rev

10.396425451504742

In [207]:
def bearish_continuation(data):
    if data["color"].iloc[-4]==0:  # Bearish Three Line Strike 
        if data["color"].iloc[-3]==0:   
            if data["color"].iloc[-2]==0:
                if data["color"].iloc[-1]==1:
                    if data["abs_body"].iloc[-4]>(data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]+data["abs_body"].iloc[-1]):
                            return 1
    if data["color"].iloc[-5]==0:  # Falling Three Methods 
        if data["color"].iloc[-4]==1:
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.2*data["abs_body"].iloc[-5]:
                            if data["close"].iloc[-2]-data["open"].iloc[-4]<data["open"].iloc[-5]-data["close"].iloc[-5]:
                                if data["close"].iloc[-2]-data["open"].iloc[-4]<data["open"].iloc[-1]-data["close"].iloc[-1]:
                                    if data["close"].iloc[-1]<data["close"].iloc[-5]:
                                        return 2
    if data["color"].iloc[-5]==0:  # Bearish Mat Hold
        if data["color"].iloc[-4]==1:
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                            if data["open"].iloc[-4]<data["close"].iloc[-5]:
                                if data["high"].iloc[-2]-data["low"].iloc[-4]<data["high"].iloc[-5]-data["low"].iloc[-5]:
                                    return 3
    return 0

In [208]:
bear_cont=0
bear_cont_ret=0
bearish_three_line_strike=0
falling_three_methods=0
bearish_mat_hold=0
bearish_three_line_strike_ret=0
falling_three_methods_ret=0
bearish_mat_hold_ret=0

In [209]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<0:
    #     continue
    # if data['taker_buy_ratio'][i]<0.5:
    #     continue 
    # if data['avg_trade_size'][i]<400:
    #     continue
    # if data['price_change_4'][i]<3.73e-05:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-06:
    #     continue
    window=data.iloc[i-5:i+1]
    pattern3=bearish_continuation(window)
    if pattern3:
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        if pattern3==1:
            bearish_three_line_strike+=1
            bearish_three_line_strike_ret+=ret
            bear_cont+=1
            bear_cont_ret+=ret
        if pattern3==2:
            if data['avg_trade_size'][i]>600:
                falling_three_methods+=1
                falling_three_methods_ret+=ret
                bear_cont+=1
                bear_cont_ret+=ret
        if pattern3==3:
            if data['avg_trade_size'][i]>400:
                bearish_mat_hold+=1
                bearish_mat_hold_ret+=ret
                bear_cont+=1
                bear_cont_ret+=ret

In [210]:
print(bearish_three_line_strike,falling_three_methods,bearish_mat_hold)

344 1 38

In [211]:
print(bearish_three_line_strike_ret/bearish_three_line_strike,falling_three_methods_ret/falling_three_methods,bearish_mat_hold_ret/bearish_mat_hold)

13.257014581395499 269.98827999999776 33.813990342105264

In [269]:
bear_cont_ret/bear_cont

14.06757926631868

In [212]:
def bullish_continuation(data):
        global bullish_three_line_strike,rising_three_methods,bullish_mat_hold
        if data["color"].iloc[-4]==1:  # Bullish Three Line Strike 
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["abs_body"].iloc[-1]>(data["abs_body"].iloc[-4]+data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]):
                            return 1
        if data["color"].iloc[-5]==1:  # Rising Three Methods 
            if data["color"].iloc[-4]==0:
                if data["color"].iloc[-3]==0:
                    if data["color"].iloc[-2]==0:
                        if data["color"].iloc[-1]==1:
                            if data["open"].iloc[-4]-data["close"].iloc[-2]<data["close"].iloc[-5]-data["open"].iloc[-5]:
                                if data["open"].iloc[-4]-data["close"].iloc[-2]<data["close"].iloc[-1]-data["open"].iloc[-1]:
                                    if data["close"].iloc[-1]>data["close"].iloc[-5]:
                                        return 2 
        return 0

In [213]:
bull_cont=0
bull_cont_ret=0
bullish_three_line_strike=0
rising_three_methods=0
bullish_mat_hold=0
bullish_three_line_strike_ret=0
rising_three_methods_ret=0
bullish_mat_hold_ret=0

In [214]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<0:
    #     continue
    # if data['taker_buy_ratio'][i]<0.44:
    #     continue 
    # if data['avg_trade_size'][i]<1000:
    #     continue
    # if data['price_change_4'][i]<3.73e-05:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-06:
    #     continue
    window=data.iloc[i-5:i+1]
    pattern4=bullish_continuation(window)
    if pattern4:
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        if pattern4==1:
            if data['taker_buy_ratio'][i]>0.44:
                bullish_three_line_strike+=1
                bullish_three_line_strike_ret+=ret
                bull_cont+=1
                bull_cont_ret+=ret
        if pattern4==2:
            rising_three_methods+=1
            rising_three_methods_ret+=ret
            bull_cont+=1
            bull_cont_ret+=ret

In [215]:
print(bullish_three_line_strike,rising_three_methods)

292 68

In [216]:
print(bullish_three_line_strike_ret/bullish_three_line_strike,rising_three_methods_ret/rising_three_methods)

9.674621982191882 66.46552969117666

In [4607]:
bull_cont_ret/bull_cont

15.776801879665792

In [ ]:
if data["color"].iloc[-2]==0:  # Bullish Engulfing
        if data["abs_body"].iloc[-2]>data["upper_wick"].iloc[-2]:
            if data["abs_body"].iloc[-2]>data["lower_wick"].iloc[-2]:
                if data["color"].iloc[-1]==1:
                    if data["body"].iloc[-1]>data["upper_wick"].iloc[-1]:
                        if data["body"].iloc[-1]>data["lower_wick"].iloc[-1]:
                            if data["body"].iloc[-1]>data["body"].iloc[-2]:

In [956]:
def bearish_reversal_high(data):
    global shooting_star,bearish_engulfing,advance_block,hanging_man,tweezer_top,evening_star
    if data["close"].iloc[-3]<data["close"].iloc[-2]:  # Shooting Star
        if data["color"].iloc[-1]==0: 
            if data["upper_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
                if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
                    return 1
    if data["close"].iloc[-6]<data["close"].iloc[-5]<data["close"].iloc[-4]:  # Advance Block
        if all(data["color"].iloc[-3:]==1):  
            if data["body"].iloc[-  3]>data["body"].iloc[-2]:
                if data["body"].iloc[-2]>data["body"].iloc[-1]:
                    if data["upper_wick"].iloc[-2]>data["upper_wick"].iloc[-3]:
                        if data["upper_wick"].iloc[-1]>data["upper_wick"].iloc[-3]:
                            if data["upper_wick"].iloc[-1]>data["upper_wick"].iloc[-2]:
                                return 3
    if data["close"].iloc[-2]<data["close"].iloc[-1]:
        if data["color"].iloc[-1]==0:  # Hanging Man
            if data["lower_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:
                if data["upper_wick"].iloc[-1]<0.1*data["lower_wick"].iloc[-1]:
                    return 4
    if data["color"].iloc[-3]==1:  # Evening Star
        if data["color"].iloc[-1]==0:
            if data["upper_wick"].iloc[-3]+data["lower_wick"].iloc[-3]<data["abs_body"].iloc[-3]:
                if data["upper_wick"].iloc[-1]+data["lower_wick"].iloc[-1]<data["abs_body"].iloc[-1]:
                    if data["abs_body"].iloc[-2]<0.2*(data["high"].iloc[-2]-data["low"].iloc[-2]):
                        if data["close"].iloc[-1]<(data["open"].iloc[-3]+data["close"].iloc[-3])/2:
                            return 6
    return 0

In [957]:
bear_rev=0
bear_rev_ret=0
shooting_star=0
bearish_engulfing=0
advance_block=0
hanging_man=0
tweezer_top=0
evening_star=0
shooting_star_ret=0
bearish_engulfing_ret=0
advance_block_ret=0
hanging_man_ret=0
tweezer_top_ret=0
evening_star_ret=0

In [ ]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<0.74:
    #     continue
    # if data['taker_buy_ratio'][i]<0.62:
    #     continue 
    # if data['avg_trade_size'][i]<2200:
    #     continue
    # if data['close_to_sma5'][i]<3.18e-03:
    #     continue
    # if data['price_change_4'][i]<0.73e-02:
    #     continue
    # if data['close_to_sma10'][i]<7.66e-03:
    #     continue
    ret=0
    window=data.iloc[i-5:i+1]
    pattern1=bearish_reversal_high(window)
    if pattern1:
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        # if pattern1==1:
        #     if data['price_change_4'][i]>0.73e-02: 
        #         shooting_star+=1
        #         shooting_star_ret+=ret
        #         bear_rev+=1
        #         bear_rev_ret+=ret
        # if pattern1==3:
        #     if data['close_to_sma10'][i]>5.66e-03: 
        #         advance_block+=1
        #         advance_block_ret+=ret
        #         bear_rev+=1
        #         bear_rev_ret+=ret
        # if pattern1==4:
        #     hanging_man+=1
        #     hanging_man_ret+=ret
        #     bear_rev+=1
        #     bear_rev_ret+=ret
        if pattern1==6:
            if data['taker_buy_ratio'][i]>0.62:
                evening_star+=1
                evening_star_ret+=ret
                bear_rev+=1
                bear_rev_ret+=ret
    else:
        continue

In [959]:
print(shooting_star,advance_block,hanging_man,evening_star)

0 0 0 586

In [960]:
evening_star_ret/evening_star

15.003955783959054

In [961]:
len([i for i in es if i>0])

283

In [604]:
print(shooting_star_ret/shooting_star,advance_block_ret/advance_block,hanging_man_ret/hanging_man,evening_star_ret/evening_star)

ZeroDivisionError: division by zero

In [3185]:
bear_rev

332

In [3187]:
bear_rev_ret/bear_rev

103.59962923192815

In [804]:
def bullish_reversal_high(data):
    global hammer,inverted_hammer,bullish_engulfing,three_stars_in_the_south,tweezer_bottom,morning_star
    if data["upper_wick"].iloc[-1]>2*data["abs_body"].iloc[-1]:  # Inverted Hammer
        if data["lower_wick"].iloc[-1]<0.2*data["upper_wick"].iloc[-1]:
            return 2
    if data["close"].iloc[-3]>data["close"].iloc[-2]:  # Bullish Engulfing
        if data["color"].iloc[-2]==0:
            if data["abs_body"].iloc[-2]>data["upper_wick"].iloc[-2]:
                if data["abs_body"].iloc[-2]>data["lower_wick"].iloc[-2]:
                    if data["color"].iloc[-1]==1:
                        if data["body"].iloc[-1]>data["upper_wick"].iloc[-1]:
                            if data["body"].iloc[-1]>data["lower_wick"].iloc[-1]:
                                if data["body"].iloc[-1]>data["body"].iloc[-2]:
                                    return 3
    if data["color"].iloc[-1]==1:  # Tweezer Bottom
        if data["color"].iloc[-2]==0:
            if data["abs_body"].iloc[-1]>data["abs_body"].iloc[-2]:
                if 0.9*data["lower_wick"].iloc[-1]<data["lower_wick"].iloc[-2]<1.1*data["lower_wick"].iloc[-1]:
                    return 5
    return 0

In [818]:
bull_rev=0
bull_rev_ret=0
hammer=0
inverted_hammer=0
bullish_engulfing=0
three_stars_in_the_south=0
tweezer_bottom=0
morning_star=0
hammer_ret=0
inverted_hammer_ret=0
bullish_engulfing_ret=0
three_stars_in_the_south_ret=0
tweezer_bottom_ret=0
morning_star_ret=0

In [ ]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<3:
    #     continue
    # if data['taker_buy_ratio'][i]<0.53:
    #     continue
    # if data['avg_trade_size'][i]<2000:
    #     continue
    # if data['price_change_4'][i]<3.73e-03:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-03:
    #     continue
    # if data['close_to_sma10'][i]<3.66e-02:
    #     continue
    ret=0
    window=data.iloc[i-5:i+1]
    pattern2=bullish_reversal_high(window)
    if pattern2:
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        if pattern2==2:
            if data['close_to_sma5'][i]>9.18e-03:
                inverted_hammer+=1
                inverted_hammer_ret+=ret
                bull_rev+=1
                bull_rev_ret+=ret
        if pattern2==3:
            if data['close_to_sma5'][i]>1.18e-02:
                bullish_engulfing+=1
                bullish_engulfing_ret+=ret
                bull_rev+=1
                bull_rev_ret+=ret
        if pattern2==5:
            if data['taker_buy_ratio'][i]>0.53:
                tweezer_bottom+=1
                tweezer_bottom_ret+=ret
                bull_rev+=1
                bull_rev_ret+=ret
    else:
        continue

In [820]:
print(hammer,inverted_hammer,bullish_engulfing,three_stars_in_the_south,tweezer_bottom,morning_star)

0 0 0 0 108 0

In [ ]:
get_ipython().cache_size=5000

In [4306]:
print(inverted_hammer_ret/inverted_hammer,bullish_engulfing_ret/bullish_engulfing,tweezer_bottom_ret/tweezer_bottom)

165.3229291153846 115.35042287999894 83.93486673239411

In [4307]:
bull_rev_ret/bull_rev

108.01798725511772

In [832]:
def bearish_continuation_high(data):
    global bearish_three_line_strike,falling_three_methods,bearish_mat_hold
    if data["color"].iloc[-5]==0:  # Bearish Mat Hold
        if data["color"].iloc[-4]==1:
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["lower_wick"].iloc[-5]+data["upper_wick"].iloc[-5]<0.5*data["abs_body"].iloc[-5]:
                            if data["open"].iloc[-4]<data["close"].iloc[-5]:
                                if data["high"].iloc[-2]-data["low"].iloc[-4]<data["high"].iloc[-5]-data["low"].iloc[-5]:
                                    return 3
    if data["color"].iloc[-4]==0:  # Bearish Three Line Strike 
        if data["color"].iloc[-3]==0:   
            if data["color"].iloc[-2]==0:
                if data["color"].iloc[-1]==1:
                    if data["abs_body"].iloc[-4]>(data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]+data["abs_body"].iloc[-1]):
                            return 4
    return 0

In [951]:
bear_cont=0
bear_cont_ret=0
bearish_three_line_strike=0
falling_three_methods=0
bearish_mat_hold=0
bearish_three_line_strike_ret=0
falling_three_methods_ret=0
bearish_mat_hold_ret=0

In [ ]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<1:
    #     continue
    # if data['taker_buy_ratio'][i]<0.6:
    #     continue 
    # if data['avg_trade_size'][i]<1600:
    #     continue
    # if data['price_change_4'][i]<3.73e-03:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-03:
    #     continue
    # if data['close_to_sma10'][i]<3.66e-04:
    #     continue
    window=data.iloc[i-5:i+1]
    pattern3=bearish_continuation_high(window)
    if pattern3:
        ret=data['close'].iloc[i]-data['close'].iloc[i+4]
        if pattern3==3:
            if data['vol_z'][i]>1:
                bearish_mat_hold+=1
                bearish_mat_hold_ret+=ret
                bear_cont+=1
                bear_cont_ret+=ret
        if pattern3==4:
            if data['close_to_sma10'][i]>3.66e-03:
                bearish_three_line_strike+=1
                bearish_three_line_strike_ret+=ret
                bear_cont+=1
                bear_cont_ret+=ret

In [953]:
print(bearish_mat_hold,bearish_three_line_strike)

4 0

In [827]:
print(bearish_mat_hold_ret/bearish_mat_hold,bearish_three_line_strike_ret/bearish_three_line_strike)

9.185882882353326 303.9114394285742

In [ ]:
bear_cont_ret/bear_cont

178.86314061363555

In [962]:
def bullish_continuation_high(data):
        global bullish_three_line_strike,rising_three_methods,bullish_mat_hold
        if data["color"].iloc[-4]==1:  # Bullish Three Line Strike 
            if data["color"].iloc[-3]==1:
                if data["color"].iloc[-2]==1:
                    if data["color"].iloc[-1]==0:
                        if data["abs_body"].iloc[-1]>(data["abs_body"].iloc[-4]+data["abs_body"].iloc[-3]+data["abs_body"].iloc[-2]):
                            return 1
        if data["color"].iloc[-5]==1:  # Rising Three Methods 
            if data["color"].iloc[-4]==0:
                if data["color"].iloc[-3]==0:
                    if data["color"].iloc[-2]==0:
                        if data["color"].iloc[-1]==1:
                            if data["open"].iloc[-4]-data["close"].iloc[-2]<data["close"].iloc[-5]-data["open"].iloc[-5]:
                                if data["open"].iloc[-4]-data["close"].iloc[-2]<data["close"].iloc[-1]-data["open"].iloc[-1]:
                                    if data["close"].iloc[-1]>data["close"].iloc[-5]:
                                        return 2 
        if data["color"].iloc[-5]==1:  # Bullish Mat Hold
            if data["color"].iloc[-4]==0:
                if data["color"].iloc[-3]==0:
                    if data["color"].iloc[-2]==0:
                        if data["color"].iloc[-1]==1:
                            if data["high"].iloc[-4]-data["low"].iloc[-2]<data["high"].iloc[-5]-data["low"].iloc[-5]:
                                if data["close"].iloc[-1]>data["high"].iloc[-5]:
                                    return 3
        return 0

In [963]:
bull_cont=0
bull_cont_ret=0
bullish_three_line_strike=0
rising_three_methods=0
bullish_mat_hold=0
bullish_three_line_strike_ret=0
rising_three_methods_ret=0
bullish_mat_hold_ret=0

In [4592]:
for i in range(5,len(data)-10):
    # if data['vol_z'][i]<2:
    #     continue
    # if data['taker_buy_ratio'][i]<0.65:
    #     continue 
    # if data['avg_trade_size'][i]<2000:
    #     continue
    # if data['price_change_4'][i]<3.73e-04:
    #     continue
    # if data['close_to_sma5'][i]<1.18e-04:
    #     continue
    window=data.iloc[i-5:i+1]
    pattern4=bullish_continuation_high(window)
    if pattern4:
        ret=data['close'].iloc[i+4]-data['close'].iloc[i]
        if pattern4==1:
            if data['price_change_4'][i]>3.73e-04:
                bullish_three_line_strike+=1
                bullish_three_line_strike_ret+=ret
                bull_cont+=1
                bull_cont_ret+=ret
        if pattern4==2:
            if data['price_change_4'][i]>3.73e-04:
                rising_three_methods+=1
                rising_three_methods_ret+=ret
                bull_cont+=1
                bull_cont_ret+=ret
        if pattern4==3:
            bullish_mat_hold+=1
            bullish_mat_hold_ret+=ret
            bull_cont+=1
            bull_cont_ret+=ret

In [4593]:
print(bullish_three_line_strike,rising_three_methods,bullish_mat_hold)

9 53 4

In [4594]:
print(bullish_three_line_strike_ret/bullish_three_line_strike,rising_three_methods_ret/rising_three_methods,bullish_mat_hold_ret/bullish_mat_hold)

103.66985133333138 91.3390197169813 126.60249999999905

In [4595]:
bull_cont_ret/bull_cont

95.15767737878768